-- VERSANTコーチング 正しい最終版レポート
-- VERSANTコーチングテーブルを使用した正しい集計

SELECT 
    c."Id" as "受講生ID",
    CONCAT(c."姓", ' ', c."名") as "受講生名",
    c."メール" as "メールアドレス",
    c."所属会社" as "会社名",
    
    -- 直近3週間の日別VERSANTコーチング回答数
    SUM(CASE WHEN DATE(vc."回答日") = DATE_SUB(CURDATE(), INTERVAL 20 DAY) THEN 1 ELSE 0 END) as "D20",
    SUM(CASE WHEN DATE(vc."回答日") = DATE_SUB(CURDATE(), INTERVAL 19 DAY) THEN 1 ELSE 0 END) as "D19",
    SUM(CASE WHEN DATE(vc."回答日") = DATE_SUB(CURDATE(), INTERVAL 18 DAY) THEN 1 ELSE 0 END) as "D18",
    SUM(CASE WHEN DATE(vc."回答日") = DATE_SUB(CURDATE(), INTERVAL 17 DAY) THEN 1 ELSE 0 END) as "D17",
    SUM(CASE WHEN DATE(vc."回答日") = DATE_SUB(CURDATE(), INTERVAL 16 DAY) THEN 1 ELSE 0 END) as "D16",
    SUM(CASE WHEN DATE(vc."回答日") = DATE_SUB(CURDATE(), INTERVAL 15 DAY) THEN 1 ELSE 0 END) as "D15",
    SUM(CASE WHEN DATE(vc."回答日") = DATE_SUB(CURDATE(), INTERVAL 14 DAY) THEN 1 ELSE 0 END) as "D14",
    SUM(CASE WHEN DATE(vc."回答日") = DATE_SUB(CURDATE(), INTERVAL 13 DAY) THEN 1 ELSE 0 END) as "D13",
    SUM(CASE WHEN DATE(vc."回答日") = DATE_SUB(CURDATE(), INTERVAL 12 DAY) THEN 1 ELSE 0 END) as "D12",
    SUM(CASE WHEN DATE(vc."回答日") = DATE_SUB(CURDATE(), INTERVAL 11 DAY) THEN 1 ELSE 0 END) as "D11",
    SUM(CASE WHEN DATE(vc."回答日") = DATE_SUB(CURDATE(), INTERVAL 10 DAY) THEN 1 ELSE 0 END) as "D10",
    SUM(CASE WHEN DATE(vc."回答日") = DATE_SUB(CURDATE(), INTERVAL 9 DAY) THEN 1 ELSE 0 END) as "D9",
    SUM(CASE WHEN DATE(vc."回答日") = DATE_SUB(CURDATE(), INTERVAL 8 DAY) THEN 1 ELSE 0 END) as "D8",
    SUM(CASE WHEN DATE(vc."回答日") = DATE_SUB(CURDATE(), INTERVAL 7 DAY) THEN 1 ELSE 0 END) as "D7",
    SUM(CASE WHEN DATE(vc."回答日") = DATE_SUB(CURDATE(), INTERVAL 6 DAY) THEN 1 ELSE 0 END) as "D6",
    SUM(CASE WHEN DATE(vc."回答日") = DATE_SUB(CURDATE(), INTERVAL 5 DAY) THEN 1 ELSE 0 END) as "D5",
    SUM(CASE WHEN DATE(vc."回答日") = DATE_SUB(CURDATE(), INTERVAL 4 DAY) THEN 1 ELSE 0 END) as "D4",
    SUM(CASE WHEN DATE(vc."回答日") = DATE_SUB(CURDATE(), INTERVAL 3 DAY) THEN 1 ELSE 0 END) as "D3",
    SUM(CASE WHEN DATE(vc."回答日") = DATE_SUB(CURDATE(), INTERVAL 2 DAY) THEN 1 ELSE 0 END) as "D2",
    SUM(CASE WHEN DATE(vc."回答日") = DATE_SUB(CURDATE(), INTERVAL 1 DAY) THEN 1 ELSE 0 END) as "D1",
    SUM(CASE WHEN DATE(vc."回答日") = CURDATE() THEN 1 ELSE 0 END) as "今日",
    
    -- 直近3週間の合計VERSANTコーチング回答数
    SUM(CASE WHEN DATE(vc."回答日") >= DATE_SUB(CURDATE(), INTERVAL 21 DAY) THEN 1 ELSE 0 END) as "3週間合計",
    ROUND(SUM(CASE WHEN DATE(vc."回答日") >= DATE_SUB(CURDATE(), INTERVAL 21 DAY) THEN 1 ELSE 0 END) / 21.0, 1) as "1日平均",
    
    -- 全期間のVERSANTコーチング回答数
    COUNT(vc."回答日") as "全期間合計",
    
    -- 学習状況の判定
    CASE 
        WHEN SUM(CASE WHEN DATE(vc."回答日") >= DATE_SUB(CURDATE(), INTERVAL 21 DAY) THEN 1 ELSE 0 END) = 0 THEN '未学習'
        WHEN SUM(CASE WHEN DATE(vc."回答日") >= DATE_SUB(CURDATE(), INTERVAL 21 DAY) THEN 1 ELSE 0 END) < 10 THEN '学習不足'
        WHEN SUM(CASE WHEN DATE(vc."回答日") >= DATE_SUB(CURDATE(), INTERVAL 21 DAY) THEN 1 ELSE 0 END) < 30 THEN '学習中'
        ELSE '積極的'
    END as "学習状況"
    
FROM "連絡先" c
INNER JOIN "手配" ar ON c."Id" = ar."連絡先ID"
LEFT JOIN "VERSANTコーチング" vc ON c."メール" = vc."メールアドレス" 
    AND vc."回答日" IS NOT NULL
WHERE ar."商品ID" IN (
    '5187347000184182087',
    '5187347000184182088', 
    '5187347000159927506'
)
GROUP BY 
    c."Id", c."姓", c."名", c."メール", c."所属会社"
ORDER BY 
    "学習状況" DESC, "3週間合計" DESC, c."姓", c."名" 